[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "smart-wallet-permissions=lib/smart-wallet-permissions",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
